---
title: "fixed effects"
format: pdf
---

## setup

```{r}
library(tidyverse)
library(here)
library(janitor)
library(broom)
library(fixest)
library(texreg)
library(knitr)

load(here("data", "df_aug2026.Rdata"))
```

# Main Analyses

## Lag 0

```{r}

# model 1: regular eg, no current partisanship
mb1_l0 <- feols(imr_b ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag0)

mw1_l0 <- feols(imr_w ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag0)

mt1_l0 <- feols(imr_t ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag0)

#model 2: regular eg, current partisanship
mb2_l0 <- feols(imr_b ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag0)

mw2_l0 <- feols(imr_w ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag0)

mt2_l0 <- feols(imr_t ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag0)
```

## Lag 1

```{r}
# model 1: regular eg, no current partisanship
mb1_l1 <- feols(imr_b ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag1)

mw1_l1 <- feols(imr_w ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag1)

mt1_l1 <- feols(imr_t ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag1)

#model 2: regular eg, current partisanship
mb2_l1 <- feols(imr_b ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag1)

mw2_l1 <- feols(imr_w ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag1)


mt2_l1 <- feols(imr_t ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag1)

```

## Lag 2

```{r}
# model 1: regular eg, no current partisanship
mb1_l2 <- feols(imr_b ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag2)

mw1_l2 <- feols(imr_w ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag2)

mt1_l2 <- feols(imr_t ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag2)

#model 2: regular eg, current partisanship
mb2_l2 <- feols(imr_b ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag2)

mw2_l2 <- feols(imr_w ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag2)

mt2_l2 <- feols(imr_t ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag2)
```

## Lag 3

```{r}
# model 1: regular eg, no current partisanship
mb1_l3 <- feols(imr_b ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag3)

mw1_l3 <- feols(imr_w ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag3)

mt1_l3 <- feols(imr_t ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z
                | state + year, 
                data = lag3)

#model 2: regular eg, current partisanship
mb2_l3 <- feols(imr_b ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag3)

mw2_l3 <- feols(imr_w ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag3)

mt2_l3 <- feols(imr_t ~ eg_z + prop_rep_planwriters_z + top10share_z + inc_z +
                  prop_rep_z | state + year, data = lag3)

```

## Model Fit

```{r}

list(mb1_l0, mb1_l1, mb1_l2, mb1_l3, mb2_l0, mb2_l1, mb2_l2, mb2_l3) |> 
  set_names(c("mb1_l0", "mb1_l1", "mb1_l2", "mb1_l3", "mb2_l0", "mb2_l1", "mb2_l2", "mb2_l3")) |> 
  map(~fitstat(.x, type = c("aic", "bic")))


list(mw1_l0, mw1_l1, mw1_l2, mw1_l3, mw2_l0, mw2_l1, mw2_l2, mw2_l3) |> 
  set_names(c("mw1_l0", "mw1_l1", "mw1_l2", "mw1_l3", "mw2_l0", "mw2_l1", "mw2_l2", "mw2_l3")) |> 
  map(~fitstat(.x, type = c("aic", "bic")))


list(mt1_l0, mt1_l1, mt1_l2, mt1_l3, mt2_l0, mt2_l1, mt2_l2, mt2_l3) |> 
  set_names(c("mt1_l0", "mt1_l1", "mt1_l2", "mt1_l3", "mt2_l0", "mt2_l1", "mt2_l2", "mt2_l3")) |> 
  map(~fitstat(.x, type = c("aic", "bic")))


```

## Main Tables

```{r}

aic <- list(mb1_l3, mw1_l3, mt1_l3, mb2_l3, mw2_l3, mt2_l3) |> 
  map(~fitstat(.x, type = "aic", verbose = F)) |> 
  tibble() |> 
  unnest_wider(1)
  
bic <- list(mb1_l3, mw1_l3, mt1_l3, mb2_l3, mw2_l3, mt2_l3) |> 
  map(~fitstat(.x, type = "bic", verbose = F)) |> 
   tibble() |> 
  unnest_wider(1)

texreg::wordreg(list(mb1_l3, mw1_l3, mt1_l3, mb2_l3, mw2_l3, mt2_l3),
                  custom.model.names = 
          c("Model 1 (Black)", 
            "Model 1 (White)",
            "Model 1 (Total)",
            "Model 2 (Black)", 
            "Model 2 (White)",
            "Model 2 (Total)"),
                  custom.coef.names = c("Efficiency Gap", "Proportion Republican: Last Redistricting", "Top 10%'s Share of Income", "Median Income", "Proportion Republican: Current"),
                  include.adjrs = F,
                  custom.gof.rows = list( 
                                         "AIC" = aic$aic,
                                         "BIC" = bic$bic),
                  reorder.gof = (c(3,4,5,1,2,6,7)),
        single.row = T,
        file = "tables_figs/mainresulttables.docx")
```

## Appendix Tables

```{r}

aic_lag0 <- list(mb1_l0, mw1_l0, mt1_l0, mb2_l0, mw2_l0, mt2_l0) |> 
  map(~fitstat(.x, type = "aic", verbose = F)) |> 
  tibble() |> 
  unnest_wider(1)

bic_lag0 <- list(mb1_l0, mw1_l0, mt1_l0, mb2_l0, mw2_l0, mt2_l0) |> 
  map(~fitstat(.x, type = "bic", verbose = F)) |> 
  tibble() |> 
  unnest_wider(1)

texreg::wordreg(list(mb1_l0, mw1_l0, mt1_l0, mb2_l0, mw2_l0, mt2_l0),
                custom.model.names = 
                  c("Model 1 (Black)", 
                    "Model 1 (White)",
                    "Model 1 (Total)",
                    "Model 2 (Black)", 
                    "Model 2 (White)",
                    "Model 2 (Total)"),
                custom.coef.names = c("Efficiency Gap", "Proportion Republican: Last Redistricting", "Top 10%'s Share of Income", "Median Income", "Proportion Republican: Current"),
                include.adjrs = F,
                custom.gof.rows = list( 
                  "AIC" = aic_lag0$aic,
                  "BIC" = bic_lag0$bic),
                reorder.gof = (c(3,4,5,1,2,6,7)),
                single.row = T,
                file = "tables_figs/suppresultstable_lag0.docx")
```

```{r}
aic_lag1 <- list(mb1_l1, mw1_l1, mt1_l1, mb2_l1, mw2_l1, mt2_l1) |> 
  map(~fitstat(.x, type = "aic", verbose = F)) |> 
  tibble() |> 
  unnest_wider(1)

bic_lag1 <- list(mb1_l1, mw1_l1, mt1_l1, mb2_l1, mw2_l1, mt2_l1) |> 
  map(~fitstat(.x, type = "bic", verbose = F)) |> 
  tibble() |> 
  unnest_wider(1)

texreg::wordreg(list(mb1_l1, mw1_l1, mt1_l1, mb2_l1, mw2_l1, mt2_l1),
                custom.model.names = 
                  c("Model 1 (Black)", 
                    "Model 1 (White)",
                    "Model 1 (Total)",
                    "Model 2 (Black)", 
                    "Model 2 (White)",
                    "Model 2 (Total)"),
                custom.coef.names = c("Efficiency Gap", "Proportion Republican: Last Redistricting", "Top 10%'s Share of Income", "Median Income", "Proportion Republican: Current"),
                include.adjrs = F,
                custom.gof.rows = list( 
                  "AIC" = aic_lag1$aic,
                  "BIC" = bic_lag1$bic),
                reorder.gof = (c(3,4,5,1,2,6,7)),
                single.row = T,
                file = "tables_figs/suppresultstable_lag1.docx")
```

```{r}
aic_lag2 <- list(mb1_l2, mw1_l2, mt1_l2, mb2_l2, mw2_l2, mt2_l2) |> 
  map(~fitstat(.x, type = "aic", verbose = F)) |> 
  tibble() |> 
  unnest_wider(1)

bic_lag2 <- list(mb1_l2, mw1_l2, mt1_l2, mb2_l2, mw2_l2, mt2_l2) |> 
  map(~fitstat(.x, type = "bic", verbose = F)) |> 
  tibble() |> 
  unnest_wider(1)

texreg::wordreg(list(mb1_l2, mw1_l2, mt1_l2, mb2_l2, mw2_l2, mt2_l2),
                custom.model.names = 
                  c("Model 1 (Black)", 
                    "Model 1 (White)",
                    "Model 1 (Total)",
                    "Model 2 (Black)", 
                    "Model 2 (White)",
                    "Model 2 (Total)"),
                custom.coef.names = c("Efficiency Gap", "Proportion Republican: Last Redistricting", "Top 10%'s Share of Income", "Median Income", "Proportion Republican: Current"),
                include.adjrs = F,
                custom.gof.rows = list( 
                  "AIC" = aic_lag2$aic,
                  "BIC" = bic_lag2$bic),
                reorder.gof = (c(3,4,5,1,2,6,7)),
                single.row = T,
                file = "tables_figs/suppresultstable_lag2.docx")
```

# Supplemental Analyses

## Absolute Value

### Lag 0

```{r}
#model 3: abs value eg, no current partisanship
mb3_l0 <-  feols(imr_b ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z 
                 | state + year, data = lag0)
mw3_l0 <-  feols(imr_w ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z 
                 | state + year, data = lag0)

#model 4: abs value eg, current partisanship
mb4_l0<- feols(imr_b ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z +
                 prop_rep_z | state + year, 
               data = lag0)
mw4_l0<- feols(imr_w ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z +
                 prop_rep_z | state + year, 
               data = lag0)
```

### Lag 1

```{r}

#model 3: abs value eg, no current partisanship
mb3_l1 <-  feols(imr_b ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z 
                 | state + year, data = lag1)
mw3_l1 <-  feols(imr_w ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z 
                 | state + year, data = lag1)

#model 4: abs value eg, current partisanship
mb4_l1<- feols(imr_b ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z +
                 prop_rep_z | state + year, 
               data = lag1)
mw4_l1<- feols(imr_w ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z +
                 prop_rep_z | state + year, 
               data = lag1)

```

### Lag 2

```{r}

#model 3: abs value eg, no current partisanship
mb3_l2 <-  feols(imr_b ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z 
                 | state + year, data = lag2)
mw3_l2 <-  feols(imr_w ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z 
                 | state + year, data = lag2)

#model 4: abs value eg, current partisanship
mb4_l2<- feols(imr_b ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z +
                 prop_rep_z | state + year, 
               data = lag2)
mw4_l2<- feols(imr_w ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z +
                 prop_rep_z | state + year, 
               data = lag2)


```

### Lag 3

```{r}

#model 3: abs value eg, no current partisanship
mb3_l3 <-  feols(imr_b ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z 
                 | state + year, data = lag3)
mw3_l3 <-  feols(imr_w ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z 
                 | state + year, data = lag3)

#model 4: abs value eg, current partisanship
mb4_l3 <- feols(imr_b ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z +
                 prop_rep_z | state + year, 
               data = lag3)
mw4_l3 <- feols(imr_w ~ eg_abs_z + prop_rep_planwriters_z + top10share_z + inc_z +
                 prop_rep_z | state + year, 
               data = lag3)

```

### Appendix Tables

```{r}
#### will get back to this
```

```{r}
save(mb1_l3, mw1_l3, mt1_l3, mb2_l3, mw2_l3, mt2_l3, file = here("data", "mainmodels.Rdata"))
```
