---
title: "Tables & Figures"
format: html
---

```{r}
#| label: setup

library(here)
library(tidyverse)
library(gtsummary)
library(colorspace)
library(broom)
library(patchwork)
library(sf)
load(here("data", "mainmodels.Rdata"))
load(here("data", "df_aug2026.Rdata"))
load(here("data", "visdata.Rdata"))
load(here("data", "preds_covs.Rdata"))
load(here("data", "states_sf.rda"))
load(here("data", "im_t.Rdata"))
load(here("data", "partisan.Rdata"))


st <- tibble(tidycensus::fips_codes) |> 
  select(state, state_name) |> 
  unique()
```

```{r}
#| label: descriptive table: sample


tbl_2018 <- lag3 |>
  drop_na() |> 
  filter(year == 2018) |> 
  tbl_summary(include = c(imr_w, imr_b, imr_t, eg,
                                     prop_rep_planwriters, prop_rep, 
                                     inc, top10share),
              label = list(imr_w = "Infant Mortality Rate (White)",
                           imr_b = "Infant Mortality Rate (Black)",
                           imr_t = "Infant Mortality Rate (Total)",
                           eg = "Efficiency Gap Score",
                           prop_rep_planwriters = "Proportion Republican: Last Redistricting",
                           prop_rep = "Proportion Republican: Current",
                           inc = "Median Income",
                           top10share = "Top 10%'s Share of Income"),
                         statistic = list(all_continuous() ~ 
                                              "{mean} ({sd})")) |> 
  modify_header(all_stat_cols() ~ "2018") |> 
  modify_footnote(all_stat_cols() ~ NA)

tbl_1995 <- lag3 |> 
  drop_na() |> 
  filter(year == 1995) |> 
  tbl_summary(include = c(imr_w, imr_b, imr_t, eg,
                                     prop_rep_planwriters, prop_rep, 
                                     inc, top10share),
              label = list(imr_w = "Infant Mortality Rate (White)",
                           imr_b = "Infant Mortality Rate (Black)",
                           imr_t = "Infant Mortality Rate (Total)",
                           eg = "Efficiency Gap Score",
                           prop_rep_planwriters = "Proportion Republican: Last Redistricting",
                           prop_rep = "Proportion Republican: Current",
                           inc = "Median Income",
                           top10share = "Top 10%'s Share of Income"),
                         statistic = list(all_continuous() ~ 
                                              "{mean} ({sd})")) |> 
  modify_header(all_stat_cols() ~ "1995") |> 
  modify_footnote(all_stat_cols() ~ NA)

tbl_full <- lag3 |> 
  drop_na() |> 
  tbl_summary(include = c(imr_w, imr_b, imr_t, eg,
                                     prop_rep_planwriters, prop_rep, 
                                     inc, top10share),
              label = list(imr_w = "Infant Mortality Rate (White)",
                           imr_b = "Infant Mortality Rate (Black)",
                           imr_t = "Infant Mortality Rate (Total)",
                           eg = "Efficiency Gap Score",
                           prop_rep_planwriters = "Proportion Republican: Last Redistricting",
                           prop_rep = "Proportion Republican: Current",
                           inc = "Median Income",
                           top10share = "Top 10%'s Share of Income"),
                         statistic = list(all_continuous() ~ 
                                              "{mean} ({sd})")) |> 
  modify_header(all_stat_cols() ~ "All Years") |> 
  modify_footnote(all_stat_cols() ~ NA)

tbl_sample <- tbl_merge(tbls = list(tbl_full, tbl_1995, tbl_2018),
          tab_spanner = FALSE)



tbl_sample
```

creating a full US dataset; want maximum data here so going back to more raw component datasets before i dropped a bunch

```{r}
preds_full <- bias |> 
  select(state, year, planyear, eg) |> 
  left_join(partisan, by = c("state", "planyear" = "year")) |> 
  rename(prop_rep_planwriters = prop_rep) |> 
  mutate(lagyear = year + 3)

outcome_full <- im |> 
  mutate(race = recode_values(race, "Non-Hispanic White" ~ "w",
                              "Non-Hispanic Black" ~ "b")) |> bind_rows(im_t) |> 
  mutate(imr = 1000 * deaths / births) |> 
  drop_na(year) |> 
  select(state, year, race, imr) |> 
  pivot_wider(id_cols = c(state, year),
              names_from = "race",
              names_prefix = "imr_",
              values_from = "imr") |> 
  rename(state_name = state) |> 
  left_join(st) |> 
  select(state, year, starts_with("imr")) |> 
  filter(year %in% c(1995:2018)) |> 
  filter(state != "DC")


us_full <- outcome_full |> 
  left_join(covs, by = c("state", "year")) |> 
  select(-ends_with("z")) |> 
  left_join(preds_full, by = c("state", "year" = "lagyear"))
```

```{r}
#| label: desc table: full US

us_1995 <- us_full |> filter(year == 1995)
us_2018 <- us_full |> filter(year == 2018)

tbl_95 <- us_1995 |> 
  tbl_summary(include = c(imr_w, imr_b, imr_t, eg,
                          prop_rep_planwriters, prop_rep,
                          inc, top10share),
              missing = "no",
              label = list(imr_w = "Infant Mortality Rate (White)",
                           imr_b = "Infant Mortality Rate (Black)",
                           imr_t = "Infant Mortality Rate (Total)",
                           eg = "Efficiency Gap Score",
                           prop_rep_planwriters = "Proportion Republican: Last Redistricting",
                           prop_rep = "Proportion Republican: Current",
                           inc = "Median Income",
                           top10share = "Top 10%'s Share of Income"),
                         statistic = list(all_continuous() ~ 
                                              "{mean} ({sd})")) |> 
  modify_header(all_stat_cols() ~ "1995") |> 
  modify_footnote(all_stat_cols() ~ NA)

tbl_18 <- us_2018 |> 
  tbl_summary(include = c(imr_w, imr_b, imr_t, eg,
                          prop_rep_planwriters, prop_rep,
                          inc, top10share),
              missing = "no",
              label = list(imr_w = "Infant Mortality Rate (White)",
                           imr_b = "Infant Mortality Rate (Black)",
                           imr_t = "Infant Mortality Rate (Total)",
                           eg = "Efficiency Gap Score",
                           prop_rep_planwriters = "Proportion Republican: Last Redistricting",
                           prop_rep = "Proportion Republican: Current",
                           inc = "Median Income",
                           top10share = "Top 10%'s Share of Income"),
                         statistic = list(all_continuous() ~ 
                                              "{mean} ({sd})")) |> 
  modify_header(all_stat_cols() ~ "2018") |> 
  modify_footnote(all_stat_cols() ~ NA)

tbl_f <- us_full |> 
  tbl_summary(include = c(imr_w, imr_b, imr_t, eg,
                          prop_rep_planwriters, prop_rep,
                          inc, top10share),
              missing = "no",
              label = list(imr_w = "Infant Mortality Rate (White)",
                           imr_b = "Infant Mortality Rate (Black)",
                           imr_t = "Infant Mortality Rate (Total)",
                           eg = "Efficiency Gap Score",
                           prop_rep_planwriters = "Proportion Republican: Last Redistricting",
                           prop_rep = "Proportion Republican: Current",
                           inc = "Median Income",
                           top10share = "Top 10%'s Share of Income"),
                         statistic = list(all_continuous() ~ 
                                              "{mean} ({sd})")) |> 
  modify_header(all_stat_cols() ~ "All Years") |> 
  modify_footnote(all_stat_cols() ~ NA)

tbl_us <- tbl_merge(tbls = list(tbl_f, tbl_95, tbl_18),
          tab_spanner = FALSE)






```

Big table

```{r}
tbl_merge(list(tbl_sample, tbl_us),
          tab_spanner = c("Sample", "Full United States")) |> 
  as_flex_table() |> 
  flextable::save_as_docx(path = here("tables_figs", "desctable.docx"))
```

```{r}
#| label: infant mortality vis
included_states <- lag3 |> 
  group_by(state) |> 
  summarize(n = n()) |> 
  pull(state)

fips <- tibble(tidycensus::fips_codes) |> 
  select(state_code, state, state_name) |> 
  unique()

im_vis <- im |> 
  mutate(race = case_match(race,
                           "Non-Hispanic White" ~ "w",
                           "Non-Hispanic Black" ~ "b")) |> 
  left_join(fips, by = c("state_code", "state" = "state_name")) |> 
  select(state = state.y, year, race, deaths, births) |> 
  filter(state %in% included_states)

im_start <- im_vis |> 
  filter(year %in% c(1995:1997)) |> 
  group_by(state, race) |> 
  summarize(deaths_start = sum(deaths),
            births_start = sum(births)) |> 
  mutate(imr_start = 1000 * deaths_start / births_start)

im_end <- im_vis |> 
  filter(year %in% c(2016:2018)) |> 
  group_by(state, race) |> 
  summarize(deaths_end = sum(deaths),
            births_end = sum(births)) |> 
  mutate(imr_end = 1000 * deaths_end / births_end)

im_df <- left_join(im_start, im_end)

imr_plot <- ggplot(im_df) +
  geom_point(aes(y = state, x = imr_end, color = race)) +
  geom_segment(aes(y = state, x = imr_end, xend = imr_start, color = race)) +
  theme_minimal() +
  scale_y_discrete(limits = rev) +
  scale_color_discrete(labels = c("Non-Hispanic\nBlack", "Non-Hispanic\nWhite")) +
  labs(y = "State",
       x = "Infant Mortality Rate\n(per 1,000 live births)",
       color = "Race")


ggsave(imr_plot,
       filename = here("figures", "imr_plot.png"),
       dpi = 300,
       width = 1080,
       height = 800,
       units = "px",
       scale = 2)
```

```{r}
eg_start <- bias |> 
  filter(state %in% included_states) |> 
  filter(year > 1991) |> 
  drop_na(eg) |> 
  group_by(state) |> 
  slice_min(year) |> 
  arrange(desc(year)) |> 
  select(state, year_start = year, eg_start = eg)

eg_end <- bias |> 
  filter(state %in% included_states) |> 
  filter(year < 2016) |> 
  drop_na(eg) |> 
  group_by(state) |> 
  slice_max(year) |> 
  arrange(year) |> 
  select(state, year_end = year, eg_end = eg)


eg_df <- left_join(eg_start, eg_end)

bias |> 
  filter(year %in% c(1992:2015)) |> 
  summarize(mean(eg, na.rm = T))

eg_df <- eg_df |> 
  arrange(state)

eg_plot <- ggplot(eg_df) + 
  geom_vline(xintercept = 0.00956, linetype = "dashed") +
  geom_point(aes(y = state, x = eg_end, color = eg_end - eg_start)) +
  geom_segment(aes(y = state, x = eg_end, xend = eg_start, color = eg_end - eg_start)) +
  scale_y_discrete(labels = rev(paste0(eg_df$state, " (", eg_df$year_start, "-", eg_df$year_end, ")")),
                   limits = rev) +
  scale_color_continuous_sequential(palette = "Red-Blue",
                                    rev = T) +
  theme_minimal() +
  labs(x = "Efficiency Gap Scores",
       y = "State (Years)",
       color = "Total Change")

ggsave(eg_plot,
       filename = here("figures", "eg_plot.png"),
       dpi = 300,
       width = 1080,
       height = 800,
       units = "px",
       scale = 2)

```

```{r}
coefb1 <- tidy(mb1_l3) |> 
  filter(str_detect(term, "eg|prop")) |> 
  select(term, est = estimate, se = std.error) |> 
  mutate(model = 1,
         race = "b")

coefb2 <- tidy(mb2_l3) |> 
  filter(str_detect(term, "eg|prop")) |> 
  select(term, est = estimate, se = std.error) |> 
  mutate(model = 2,
         race = "b")


#################################
coefw1 <- tidy(mw1_l3) |> 
  filter(str_detect(term, "eg|prop")) |> 
  select(term, est = estimate, se = std.error) |> 
  mutate(model = 1,
         race = "w")

coefw2 <- tidy(mw2_l3) |> 
  filter(str_detect(term, "eg|prop")) |> 
  select(term, est = estimate, se = std.error) |> 
  mutate(model = 2,
         race = "w")


###################################
coeft1 <- tidy(mt1_l3) |> 
  filter(str_detect(term, "eg|prop")) |> 
  select(term, est = estimate, se = std.error) |> 
  mutate(model = 1,
         race = "t")

coeft2 <- tidy(mt2_l3) |> 
  filter(str_detect(term, "eg|prop")) |> 
  select(term, est = estimate, se = std.error) |> 
  mutate(model = 2,
         race = "t")


coefs <- bind_rows(coefb1, coefb2, coefw1, coefw2,
                   coeft1, coeft2)

```

```{r}

coefplot_b <- coefs |> 
  filter(race == "b") |> 
  mutate(term = fct_relevel(term, "prop_rep_z", "prop_rep_planwriters_z", "eg_z"),
         model = case_match(model,
                            1 ~ "Model 1",
                            2 ~ "Model 2"),
         race = fct(race, levels = c("b", "w", "t"))) |> 
  ggplot(aes(y = term)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(aes(x = est, color = race)) +
  geom_segment(aes(x = est + 1.96*se, xend = est - 1.96*se, color = race)) +
    scale_color_manual(values = c("tomato")) +
    xlim(-.6, .9) +
  facet_wrap("model") +
  scale_y_discrete(labels = c("Proportion Republican:\nCurrent", "Proportion Republican:\nLast Redistricting", "Efficiency Gap")) +
  theme_minimal() +
  labs(x = "Estimates and 95% Confidence Intervals",
       y = "Variable",
       color = "") +
  theme(legend.position = "none")

coefplot_w <- coefs |> 
  filter(race == "w") |> 
  mutate(term = fct_relevel(term, "prop_rep_z", "prop_rep_planwriters_z", "eg_z"),
         model = case_match(model,
                            1 ~ "Model 1",
                            2 ~ "Model 2"),
         race = fct(race, levels = c("b", "w", "t"))) |> 
  ggplot(aes(y = term)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(aes(x = est, color = race)) +
  geom_segment(aes(x = est + 1.96*se, xend = est - 1.96*se, color = race)) +
  scale_color_manual(values = c("turquoise3")) +
  facet_wrap("model") +
  xlim(-.6, .9) +
  scale_y_discrete(labels = c("Proportion Republican:\nCurrent", "Proportion Republican:\nLast Redistricting", "Efficiency Gap")) +
  theme_minimal() +
  labs(x = "Estimates and 95% Confidence Intervals",
       y = "Variable",
       color = "") +
  theme(legend.position = "none")

coefplot_t <- coefs |> 
  filter(race == "t") |> 
  mutate(term = fct_relevel(term, "prop_rep_z", "prop_rep_planwriters_z", "eg_z"),
         model = case_match(model,
                            1 ~ "Model 1",
                            2 ~ "Model 2"),
         race = fct(race, levels = c("b", "w", "t"))) |> 
  ggplot(aes(y = term)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(aes(x = est, color = race)) +
  geom_segment(aes(x = est + 1.96*se, xend = est - 1.96*se, color = race)) +
  scale_color_manual(values = c("purple3")) +
  facet_wrap("model") +
  xlim(-.6, .9) +
  scale_y_discrete(labels = c("Proportion Republican:\nCurrent", "Proportion Republican:\nLast Redistricting", "Efficiency Gap")) +
  theme_minimal() +
  labs(x = "Estimates and 95% Confidence Intervals",
       y = "Variable",
       color = "") +
  theme(legend.position = "none")

coefplot <- coefplot_b +
  coefplot_w +
  coefplot_t +
  plot_layout(ncol = 1,
              axes = "collect") +
  plot_annotation(tag_levels = list(c("Non-Hispanic Black", "Non-Hispanic White", "Total"))) &
                  theme(plot.tag.position = "right",
                        plot.tag = element_text(angle = -90, size = 10))

coefplot

ggsave(coefplot,
       filename = here("tables_figs", "coef_plot.png"),
       dpi = 300,
       width = 800,
       height = 1080,
       units = "px",
       scale = 2)
```

```{r}
#| label: map of included states

included_states <- lag3 |> 
  group_by(state) |> 
  tally() |> 
  pull(state)

map_data <- tibble(state = state.name,
       st = state.abb) |> 
  mutate(include = case_when(st %in% included_states ~ 1,
                             .default = 0))

statemap <- left_join(states_sf, map_data, by = c("state", "st"))


statemap |> 
  ggplot() +
  geom_sf(aes(fill = as.factor(include))) +
  scale_fill_manual(values = c("gray90", "tomato")) +
  theme_void() +
  theme(legend.position = "none")

```

```{r}
#| label: alt charts for presentation

coefs |> 
  filter(model == 1) |> 
  mutate(term = fct_relevel(term, "prop_rep_planwriters_z", "eg_z"),
         race = factor(race, levels = c("b", "w", "t"),
                    labels = c("NH Black",
                               "NH White",
                               "Total"))) |> 
  ggplot(aes(y = term)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(aes(x = est, color = race)) +
  geom_segment(aes(x = est + 1.96*se, xend = est - 1.96*se, color = race)) +
  scale_color_manual(labels = c("Black", "White", "Total"), values = c("tomato", "turquoise3", "purple3")) +
  xlim(-.6, .9) +
  facet_wrap("race") +
  scale_y_discrete(labels = c("Proportion Republican:\nLast Redistricting", "Efficiency Gap")) +
  theme_minimal() +
  labs(x = "Estimates and 95% Confidence Intervals",
       y = "Variable",
       color = "") +
  theme(legend.position = "none")

coefs |> 
  filter(model == 2) |> 
  mutate(term = fct_relevel(term, "prop_rep_z", "prop_rep_planwriters_z", "eg_z"),
         race = factor(race, levels = c("b", "w", "t"),
                       labels = c("NH Black",
                                  "NH White",
                                  "Total"))) |> 
  ggplot(aes(y = term)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(aes(x = est, color = race)) +
  geom_segment(aes(x = est + 1.96*se, xend = est - 1.96*se, color = race)) +
  scale_color_manual(labels = c("Black", "White", "Total"), values = c("tomato", "turquoise3", "purple3")) +
  xlim(-.6, .9) +
  facet_wrap("race") +
  scale_y_discrete(labels = c("Proportion Republican:\nConcurrent", "Proportion Republican:\nLast Redistricting", "Efficiency Gap")) +
  theme_minimal() +
  labs(x = "Estimates and 95% Confidence Intervals",
       y = "Variable",
       color = "") +
  theme(legend.position = "none")
```
